-- public.tab_lancamento definition

-- Drop table

-- DROP TABLE public.tab_lancamento;

CREATE TABLE public.tab_lancamento (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	des_lancamento text NULL,
	ind_entrada_saida int4 NOT NULL,
	val_lancamento numeric NOT NULL,
	dta_lancamento timestamp NOT NULL,
	dta_create_at timestamp NOT NULL,
	dta_updated_at timestamp NOT NULL,
	CONSTRAINT "PK_tab_lancamento" PRIMARY KEY (id)
);